### PR TITLE
Updating the Microsoft Edge logo to the modern version

### PR DESCRIPTION
**Pull request by gregwhitworth**

### CODE REVIEW

**Comment by stevefaulkner** [comment]
@gregwhitworth thanks, so as far as API support goes, am thinking of ignoring UIA for the moment and reporting the Ia2 support, thoughts?

**Comment by gregwhitworth** [comment]
@stevefaulkner we should discuss that further as we put a ton of work into UIA and did our testing against that. We also did IA2 testing as well since we had to ship to Mac but we had no desire to regress our users in any way. The testing currently states where it was done and how and given that we have a UIA implementation shipping on by default and can report that it was tested on Windows I don't see a need for a change.

**Comment by gregwhitworth** [comment]
Now, I can also update the version that was tested in Microsoft Edge. I did not test Chrome but did ensure that the issues that were listed for them do not repro in Edge.

**Comment by stevefaulkner** [comment]
@gregwhitworth thanks, so as far as UIA goes the new edge has the same support as the old edge?

**Comment by stevefaulkner** [comment]
@gregwhitworth am a little confused by this statement as Mac does not use Ia2, it uses AXAPI

> We also did IA2 testing as well since we had to ship to Mac

**Comment by gregwhitworth** [comment]
@stevefaulkner You're correct, I didn't actively work on the Mac variant so I misspoke; I apologize. Regarding UIA it is similar to the work discussed [here](https://blogs.windows.com/msedgedev/2016/04/20/building-a-more-accessible-web-platform/). It should be 100% the same and from our testing of html5accessibility it works as intended. During our testing of HTML5Accessibility.com we found ~44 sub tests that failed (so thank you for the site 😁). Many of those were the result of a few bugs that fixed them. We also changed the controls quite a bit so it allowed us to accomplish a test of UIA and the new controls at the same time and get new tests into Chromium to cover these. Let me know if you have any further questions.

**Comment by stevefaulkner** [comment]
@gregwhitworth would it be true to say that both chrome and edge have same level of support for UIA and Ia2?

**Comment by gregwhitworth** [comment]
> would it be true to say that both chrome and edge have same level of support for UIA and Ia2?

No, they have not enabled the UIA implementation in Chrome yet although all of the UIA work did happen in Chromium so they have the code they just have that part of the codepath turned off. Our IA2 implementation is indeed a 1:1 with what you see in Chrome. Once they enable it they will be the same as us.

**Comment by gregwhitworth** [comment]
@stevefaulkner just a friendly ping

**Pull request merged**
