### PR TITLE
Make minor improvements

### PR DESCRIPTION
**Pull request by alrra**
- Update the browser logos (see commit message for more details).
  - Before
    
  - After
    
- Remove unused images.     
- Losslessly optimize images.

### CODE REVIEW

**Comment by dstorey** [comment]
Updates to index-temp is irrelevant as it was just a holding place for the old page while working on the new one.

The existing IE logo was used on purpose as it is the one used by "metro" IE in Windows 8, and in branding situations (modern.ie used that logo for example). The other icons got wiped out in a merge conflict, but I have the new icons in the correct size, that I hand optimised to the lowest bit-depth, so I can put those back (fixing merge conflicts with a binary file is a pita)

**Comment by alrra** [comment]
@dstorey Thanks for the feedback! 

--

> The existing IE logo was used on purpose as it is the one used by "metro" IE in Windows 8, and in branding situations (modern.ie used that logo for example).

Reverted that change.

> Updates to index-temp is irrelevant as it was just a holding place for the old page while working on the new one. 
>
> Most of those optimised images in this PR are actually not used any longer 

I only removed the images that aren't used anywhere. As for the rest, I think they should be removed when the page that uses them is also removed.

> . The Edge logo also isn't used, as an SVG version of the Edge logo and the simplified IE logo is used instead.

Reverted that change., but corrected the color in the `svg` version of the logo.

--

Let me know if you want me to change anything else! Also, feel free to merge only what you think is necessary. :)

**Comment by alrra** [comment]
Friendly ping @dstorey  👋

**Comment by stevefaulkner** [comment]
@dstorey your call on this PR?

**Pull request closed without merging**
